services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_INDEXER_URL: ${NEXT_PUBLIC_INDEXER_URL}
        NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_CHAIN: ${NEXT_PUBLIC_CHAIN}
        NEXT_PUBLIC_TESTNET_RPC_URL: ${NEXT_PUBLIC_TESTNET_RPC_URL}
    ports:
      - "127.0.0.1:${PORT:-3001}:3000"
    env_file:
      - .env
    restart: unless-stopped
